package com.runningapp.app.ui.theme
import androidx.compose.ui.graphics.Color

val custom_color_yellow = Color(0xFFE9BE59)
val custom_color_red = Color(0xFFD34646)
val custom_color_blue = Color(0xFF01BAEF)
val custom_color_green = Color(0xFF32B630)

val ShimmerColorShades = listOf(
    Color.LightGray.copy(0.4f),
    Color.LightGray.copy(0.1f),
    Color.LightGray.copy(0.4f)
)

val md_theme_light_primary = Color(0xFF004dec)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFdbe1ff)
val md_theme_light_onPrimaryContainer = Color(0xFF001454)
val md_theme_light_secondary = Color(0xFF595d71)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFdee1f9)
val md_theme_light_onSecondaryContainer = Color(0xFF161b2c)
val md_theme_light_tertiary = Color(0xFF0061a6)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFd0e4ff)
val md_theme_light_onTertiaryContainer = Color(0xFF001d36)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfefbff)
val md_theme_light_onBackground = Color(0xFF1b1b1f)
val md_theme_light_surface = Color(0xFFfefbff)
val md_theme_light_onSurface = Color(0xFF1b1b1f)
val md_theme_light_surfaceVariant = Color(0xFFe2e1ec)
val md_theme_light_onSurfaceVariant = Color(0xFF45464e)
val md_theme_light_outline = Color(0xFF76767f)
val md_theme_light_inverseOnSurface = Color(0xFFf3f0f5)
val md_theme_light_inverseSurface = Color(0xFF303033)

val md_theme_dark_primary = Color(0xFFb5c4ff)
val md_theme_dark_onPrimary = Color(0xFF002583)
val md_theme_dark_primaryContainer = Color(0xFF0038b8)
val md_theme_dark_onPrimaryContainer = Color(0xFFdbe1ff)
val md_theme_dark_secondary = Color(0xFFc2c5dd)
val md_theme_dark_onSecondary = Color(0xFF2b2f42)
val md_theme_dark_secondaryContainer = Color(0xFF424659)
val md_theme_dark_onSecondaryContainer = Color(0xFFdee1f9)
val md_theme_dark_tertiary = Color(0xFF9ccaff)
val md_theme_dark_onTertiary = Color(0xFF00325a)
val md_theme_dark_tertiaryContainer = Color(0xFF00497f)
val md_theme_dark_onTertiaryContainer = Color(0xFFd0e4ff)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1b1b1f)
val md_theme_dark_onBackground = Color(0xFFe4e2e6)
val md_theme_dark_surface = Color(0xFF1b1b1f)
val md_theme_dark_onSurface = Color(0xFFe4e2e6)
val md_theme_dark_surfaceVariant = Color(0xFF45464e)
val md_theme_dark_onSurfaceVariant = Color(0xFFc6c6d0)
val md_theme_dark_outline = Color(0xFF909099)
val md_theme_dark_inverseOnSurface = Color(0xFF1b1b1f)
val md_theme_dark_inverseSurface = Color(0xFFe4e2e6)

val seed = Color(0xFF2962ff)
val error = Color(0xFFba1b1b)